In [8]:
# Load the Boston dataset

from sklearn.datasets import load_boston
boston = load_boston()
print(type(boston))

<class 'sklearn.utils.Bunch'>


In [9]:
# Datasets are simple objects

boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR'])

In [13]:
# The 'data' key holds the feature values

type(boston['data'])

numpy.ndarray

In [15]:
# To see the feature names 

boston['feature_names']


array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'],
      dtype='<U7')

In [16]:
# The overall description of the dataset
print(boston['DESCR'])

Boston House Prices dataset

Notes
------
Data Set Characteristics:  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive
    
    :Median Value (attribute 14) is usually the target

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pupil-teacher ratio by town
      

In [17]:
boston['data'][0]


array([  6.32000000e-03,   1.80000000e+01,   2.31000000e+00,
         0.00000000e+00,   5.38000000e-01,   6.57500000e+00,
         6.52000000e+01,   4.09000000e+00,   1.00000000e+00,
         2.96000000e+02,   1.53000000e+01,   3.96900000e+02,
         4.98000000e+00])

In [20]:
# We'll use the RandomForestRegressor to fit the model.

from sklearn.ensemble import RandomForestRegressor
clf = RandomForestRegressor()
clf.fit(boston.data, boston.target)   # Execute the classifier against the data and target

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [21]:
clf.score(boston.data, boston.target)

0.97080486292447787

In [25]:
clf.score?


In [28]:
# What features were used in the model?  The end in _
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_cache',
 '_abc_negative_cache',
 '_abc_negative_cache_version',
 '_abc_registry',
 '_estimator_type',
 '_get_param_names',
 '_make_estimator',
 '_set_oob_score',
 '_validate_X_predict',
 '_validate_estimator',
 '_validate_y_class_weight',
 'apply',
 'base_estimator',
 'base_estimator_',
 'bootstrap',
 'class_weight',
 'criterion',
 'decision_path',
 'estimator_params',
 'estimators_',
 'feature_importances_',
 'fit',
 'get_params',
 'max_depth',
 'max_features',
 'max_leaf_nodes',
 'min_impurity_decrease',
 'min_impuri

In [29]:
clf.n_features_


13

In [30]:
boston.data.shape

(506, 13)

In [31]:
row = boston.data[17]
row.shape

(13,)

In [32]:
row.reshape(-1, 13)

array([[   0.7842,    0.    ,    8.14  ,    0.    ,    0.538 ,    5.99  ,
          81.7   ,    4.2579,    4.    ,  307.    ,   21.    ,  386.75  ,
          14.67  ]])

In [33]:
# The model predicted a vaue (in $1000 US increments) of:
clf.predict(row.reshape(-1,13))

array([ 18.48])

In [35]:
# The actual sales price
boston.target[17]

17.5