In [86]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [87]:
# Create an array of 50 elements, reshape it to a 10 (row) x 5 (column) matrix
arr = np.arange(50).reshape((10,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [88]:
# Transpose - flip the dimensions, thus making it a 5 x 10 matrix
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49]])

In [89]:
# Dot product
np.dot(arr.T,arr)

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

In [90]:
np.sqrt(arr)

array([[ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ],
       [ 2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ],
       [ 3.16227766,  3.31662479,  3.46410162,  3.60555128,  3.74165739],
       [ 3.87298335,  4.        ,  4.12310563,  4.24264069,  4.35889894],
       [ 4.47213595,  4.58257569,  4.69041576,  4.79583152,  4.89897949],
       [ 5.        ,  5.09901951,  5.19615242,  5.29150262,  5.38516481],
       [ 5.47722558,  5.56776436,  5.65685425,  5.74456265,  5.83095189],
       [ 5.91607978,  6.        ,  6.08276253,  6.164414  ,  6.244998  ],
       [ 6.32455532,  6.40312424,  6.4807407 ,  6.55743852,  6.63324958],
       [ 6.70820393,  6.78232998,  6.8556546 ,  6.92820323,  7.        ]])

In [91]:
np.exp(arr)

array([[  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
          2.00855369e+01,   5.45981500e+01],
       [  1.48413159e+02,   4.03428793e+02,   1.09663316e+03,
          2.98095799e+03,   8.10308393e+03],
       [  2.20264658e+04,   5.98741417e+04,   1.62754791e+05,
          4.42413392e+05,   1.20260428e+06],
       [  3.26901737e+06,   8.88611052e+06,   2.41549528e+07,
          6.56599691e+07,   1.78482301e+08],
       [  4.85165195e+08,   1.31881573e+09,   3.58491285e+09,
          9.74480345e+09,   2.64891221e+10],
       [  7.20048993e+10,   1.95729609e+11,   5.32048241e+11,
          1.44625706e+12,   3.93133430e+12],
       [  1.06864746e+13,   2.90488497e+13,   7.89629602e+13,
          2.14643580e+14,   5.83461743e+14],
       [  1.58601345e+15,   4.31123155e+15,   1.17191424e+16,
          3.18559318e+16,   8.65934004e+16],
       [  2.35385267e+17,   6.39843494e+17,   1.73927494e+18,
          4.72783947e+18,   1.28516001e+19],
       [  3.49342711e+19,   9.4961194

In [92]:
A = np.random.randn(10)
B = np.random.randn(10)



In [93]:
A

array([ 0.5863255 ,  1.28391013, -2.39937714, -0.10486979,  0.30144187,
       -1.79545756, -2.52393082, -0.29344653,  0.54120609, -0.80111332])

In [94]:
B

array([ 0.33334833, -0.07706903,  1.36110309,  0.54074726, -0.12900784,
       -1.47017134,  0.30283903,  1.45153079, -0.36844986, -0.56699923])

### Binary Functions "ufunc"

Binary functions take two arrays
https://docs.scipy.org/doc/numpy-1.13.0/reference/ufuncs.html#available-ufuncs


In [95]:
np.add(A,B)  # Add each value

array([ 0.91967383,  1.2068411 , -1.03827404,  0.43587747,  0.17243404,
       -3.26562889, -2.22109179,  1.15808426,  0.17275623, -1.36811254])

In [96]:
np.maximum(A,B)  # Compare values in A & B return the maximum

array([ 0.5863255 ,  1.28391013,  1.36110309,  0.54074726,  0.30144187,
       -1.47017134,  0.30283903,  1.45153079,  0.54120609, -0.56699923])

In [97]:
### List Comprehensions on arrays

In [98]:
A = np.array([1,2,3,4])
B = np.array([100,200,300,400])
condition = np.array([True, True, False, False])
# Make array where we choose the A value if condition is true, otherwise choose B value
answer = [(A_val if cond else B_val) for A_val,B_val,cond in zip(A,B,condition)]

In [99]:
answer

[1, 2, 300, 400]

In [37]:
# Where clause style
# Where condition=true, A - where condition=false, B
np.where(condition,A,B)

array([  1,   2, 300, 400])

In [45]:
a2 = np.random.randn(5,5)
a2

array([[ 0.75247174,  2.2466212 , -1.00489624,  0.03451075,  0.16237173],
       [ 1.08578213, -0.47533674, -0.8206567 ,  0.42677446, -0.23729853],
       [ 0.3559847 ,  0.94139933,  0.82889493,  0.28807267, -1.0125613 ],
       [-0.11110754, -0.09258405,  1.41487525, -0.16603399, -0.52089344],
       [ 1.64120638,  1.36375446,  2.00202639, -0.99720203,  0.22736892]])

In [48]:
np.where(a2<0, 0, a2) # Replace negative values with 0

array([[ 0.75247174,  2.2466212 ,  0.        ,  0.03451075,  0.16237173],
       [ 1.08578213,  0.        ,  0.        ,  0.42677446,  0.        ],
       [ 0.3559847 ,  0.94139933,  0.82889493,  0.28807267,  0.        ],
       [ 0.        ,  0.        ,  1.41487525,  0.        ,  0.        ],
       [ 1.64120638,  1.36375446,  2.00202639,  0.        ,  0.22736892]])

In [51]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [57]:
arr2 = np.arange(1,10).reshape((3,3))
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
if (np.array_equal(arr,arr2)):
    print("Equal!")
else:
    print("Not hotdog!")

Equal!


In [68]:
arr.sum() # Sum the whole array

45

In [69]:
arr.sum(0) # sum a column

array([12, 15, 18])

In [70]:
arr.mean() # mean

5.0

In [71]:
arr.std() # standard deviation

2.5819888974716112

In [72]:
arr.var() # variation

6.666666666666667

In [73]:
bool_arr = np.array([True,False,True])


In [74]:
bool_arr.any() # Any true?

True

In [75]:
bool_arr.all() # All true?

False

In [78]:
arr = np.random.randn(5)
arr

array([ 1.47901114,  0.70007154, -0.14181017, -0.05089944,  0.64632107])

In [80]:
arr.sort()
arr

array([-0.14181017, -0.05089944,  0.64632107,  0.70007154,  1.47901114])

In [82]:
countries = np.array(['France', 'Germany', 'USA', 'Russia', 'USA', 'Mexico', 'Germany'])
np.unique(countries)

array(['France', 'Germany', 'Mexico', 'Russia', 'USA'],
      dtype='<U7')

In [84]:
np.in1d(['France', 'USA', 'Sweden'], countries) # Check if every element in arg1 is present in the 1d array of countries

array([ True,  True, False], dtype=bool)