## Explore basic saving/loading of numpy arrays


In [1]:
import numpy as np

In [2]:
arr = np.arange(5)

In [3]:
arr

array([0, 1, 2, 3, 4])

In [4]:
# Save an array

np.save('./output/myarray_example', arr)

In [5]:
arr = "dereferenced"

In [6]:
arr

'dereferenced'

In [7]:
# Load an array
arr = np.load('./output/myarray_example.npy')

In [8]:
arr

array([0, 1, 2, 3, 4])

In [9]:
arr1 = np.load('./output/myarray_example.npy')
arr2 = np.arange(10)

In [10]:
np.savez('./output/ziparray.npz', x=arr1, y=arr2)

In [11]:
archive_array = np.load('./output/ziparray.npz')

In [12]:
archive_array['x']

array([0, 1, 2, 3, 4])

In [13]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr = np.array([[1,2,4],[4,5,6]])

In [15]:
arr

array([[1, 2, 4],
       [4, 5, 6]])

In [16]:
np.savetxt('./output/somearray.txt', arr,delimiter=',')

In [19]:
from_text = np.loadtxt('./output/somearray.txt',delimiter=',')

In [20]:
from_text

array([[ 1.,  2.,  4.],
       [ 4.,  5.,  6.]])